# Generated by Django 3.2 on 2021-05-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribemodel',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
