# Generated by Django 3.2 on 2021-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_alter_subscribemodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('subheading', models.CharField(blank=True, max_length=500, null=True)),
                ('post', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
