# Generated by Django 3.2 on 2021-05-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_newsletteremail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremail',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='newsletter'),
        ),
    ]
