# Generated by Django 3.2 on 2021-05-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobilenumber',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
