# Generated by Django 3.2 on 2021-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='user_dp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobilenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
