# Generated by Django 3.2 on 2021-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
