# Generated by Django 3.2 on 2021-05-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='blogger',
            name='metades',
            field=models.CharField(default='new post', max_length=300),
        ),
        migrations.AddField(
            model_name='blogger',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogger',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish'), (2, 'Delete')], default=0),
        ),
        migrations.AddField(
            model_name='blogger',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
