# Generated by Django 3.2 on 2021-05-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210506_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogger',
            options={},
        ),
    ]
